// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo

#include "textflag.h"

// these stubs are here because it is not possible to go:linkname directly the C functions

TEXT ___errno_location(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure___errno_location(SB)

TEXT _setegid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setegid(SB)

TEXT _seteuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_seteuid(SB)

TEXT _setgid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setgid(SB)

TEXT _setregid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setregid(SB)

TEXT _setresgid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setresgid(SB)

TEXT _setresuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setresuid(SB)

TEXT _setreuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setreuid(SB)

TEXT _setuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setuid(SB)

TEXT _setgroups(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setgroups(SB)

TEXT _pthread_attr_getstacksize(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_attr_getstacksize(SB)

TEXT _pthread_attr_destroy(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_attr_destroy(SB)
