// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && (darwin || freebsd || linux || netbsd)

#include "textflag.h"

// these stubs are here because it is not possible to go:linkname directly the C functions

TEXT _malloc(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_malloc(SB)

TEXT _free(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_free(SB)

TEXT _setenv(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_setenv(SB)

TEXT _unsetenv(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_unsetenv(SB)

TEXT _sigfillset(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_sigfillset(SB)

TEXT _nanosleep(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_nanosleep(SB)

TEXT _abort(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_abort(SB)

TEXT _pthread_attr_init(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_attr_init(SB)

TEXT _pthread_create(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_create(SB)

TEXT _pthread_detach(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_detach(SB)

TEXT _pthread_sigmask(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_sigmask(SB)

TEXT _pthread_mutex_lock(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_mutex_lock(SB)

TEXT _pthread_mutex_unlock(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_mutex_unlock(SB)

TEXT _pthread_cond_broadcast(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_cond_broadcast(SB)

TEXT _pthread_setspecific(SB), NOSPLIT|NOFRAME, $0-0
	JMP pure_pthread_setspecific(SB)
